version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.9
  - dependency-name: html-entities
    versions:
    - 2.0.2
    - 2.1.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: jest-silent-reporter
    versions:
    - 0.4.0
  - dependency-name: commander
    versions:
    - 7.0.0
